<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>AnyCPU;x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TieredPGO>true</TieredPGO>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <OptimizationPreference>Speed</OptimizationPreference>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <AssemblyTitle>Clocky</AssemblyTitle>
    <Product>Clocky</Product>
    <Version>1.0.3</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\icon.png" />
    <Resource Include="Assets\icon.ico" />
    <Resource Include="Assets\clocky_title_dark.png" />
    <Resource Include="Assets\clocky_title_light.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
  </ItemGroup>

</Project>
